# Generated by Django 4.1.7 on 2023-04-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='protocolo',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
