# Generated by Django 4.1.7 on 2023-03-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_email_alter_cliente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
