# Generated by Django 4.1.7 on 2023-04-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='slug',
        ),
    ]
